# Generated by Django 4.1.3 on 2022-11-17 20:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None, max_length=15, null=True, region=None, unique=True
            ),
        ),
    ]
